
import jsPDF from 'jspdf';
import { format } from 'date-fns';

interface EmergencyFundTransaction {
    id: string;
    action_type: 'deposit' | 'withdrawal' | 'external_withdrawal';
    amount: number;
    note: string | null;
    initiating_user: string;
    created_at: string;
}

export const exportEmergencyFundToPDF = async (
    transactions: EmergencyFundTransaction[],
    currentBalance: number,
    adminName: string
) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;
    let yPosition = margin;

    // Header
    doc.setFillColor(16, 185, 129); // Emerald-500
    doc.rect(0, 0, pageWidth, 50, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Lighthouse Cashbook', margin, 25);

    doc.setFontSize(16);
    doc.text('Emergency Fund Audit Report', margin, 40);

    yPosition = 70;

    // Fund Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Current Reserve Balance: ZMW ${currentBalance.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, margin, yPosition);
    yPosition += 10;
    doc.text(`Generated By: ${adminName}`, margin, yPosition);
    yPosition += 20;

    // Summary Stats
    const totalDeposits = transactions
        .filter(t => t.action_type === 'deposit')
        .reduce((sum, t) => sum + t.amount, 0);

    const totalWithdrawals = transactions
        .filter(t => t.action_type !== 'deposit')
        .reduce((sum, t) => sum + t.amount, 0);

    doc.setFontSize(12);
    doc.text('Performance Summary', margin, yPosition);
    yPosition += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.text(`Total Deposits into Fund: ZMW ${totalDeposits.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, margin, yPosition);
    yPosition += 8;
    doc.text(`Total Withdrawals from Fund: ZMW ${totalWithdrawals.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, margin, yPosition);
    yPosition += 8;
    doc.text(`Transaction Count: ${transactions.length}`, margin, yPosition);
    yPosition += 20;

    // Table Headers
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);

    const headers = ['Date', 'Action', 'Amount (ZMW)', 'Initiated By', 'Memo'];
    const colWidths = [35, 40, 40, 30, 45];
    let xPosition = margin;

    // Draw header background
    doc.setFillColor(240, 253, 244); // Light emerald
    doc.rect(margin, yPosition - 5, pageWidth - (2 * margin), 15, 'F');

    headers.forEach((header, index) => {
        doc.text(header, xPosition, yPosition + 5);
        xPosition += colWidths[index];
    });

    yPosition += 20;

    // Table Rows
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);

    transactions.forEach((t, index) => {
        // Check if we need a new page
        if (yPosition > pageHeight - 30) {
            doc.addPage();
            yPosition = margin;

            // Re-draw headers on new page
            doc.setFont('helvetica', 'bold');
            doc.setFillColor(240, 253, 244);
            doc.rect(margin, yPosition - 5, pageWidth - (2 * margin), 15, 'F');
            let headerX = margin;
            headers.forEach((header, i) => {
                doc.text(header, headerX, yPosition + 5);
                headerX += colWidths[i];
            });
            yPosition += 20;
            doc.setFont('helvetica', 'normal');
        }

        // Alternating row colors
        if (index % 2 === 0) {
            doc.setFillColor(250, 255, 252);
            doc.rect(margin, yPosition - 3, pageWidth - (2 * margin), 12, 'F');
        }

        xPosition = margin;

        // Date
        doc.text(format(new Date(t.created_at), 'dd/MM/yyyy'), xPosition, yPosition + 5);
        xPosition += colWidths[0];

        // Action
        let actionLabel = '';
        switch (t.action_type) {
            case 'deposit': actionLabel = 'Deposit'; break;
            case 'withdrawal': actionLabel = 'Return'; break;
            case 'external_withdrawal': actionLabel = 'Direct Withdraw'; break;
            default: actionLabel = t.action_type;
        }
        doc.text(actionLabel, xPosition, yPosition + 5);
        xPosition += colWidths[1];

        // Amount
        const amountStr = t.amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
        if (t.action_type === 'deposit') {
            doc.setTextColor(0, 150, 0);
            doc.text(`+${amountStr}`, xPosition, yPosition + 5);
        } else {
            doc.setTextColor(200, 0, 0);
            doc.text(`-${amountStr}`, xPosition, yPosition + 5);
        }
        doc.setTextColor(0, 0, 0);
        xPosition += colWidths[2];

        // User
        doc.text(t.initiating_user || 'Admin', xPosition, yPosition + 5);
        xPosition += colWidths[3];

        // Memo
        const memo = t.note || '-';
        doc.text(memo.substring(0, 25), xPosition, yPosition + 5);

        yPosition += 12;
    });

    // Footer
    yPosition = pageHeight - 20;
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`Emergency Fund Audit | Generated on ${format(new Date(), 'PPpp')}`, margin, yPosition);
    doc.text(`Page ${doc.getNumberOfPages()}`, pageWidth - margin - 20, yPosition);

    // Save
    const filename = `Emergency_Fund_Report_${format(new Date(), 'yyyyMMdd_HHmm')}.pdf`;
    doc.save(filename);
};
