
import jsPDF from 'jspdf';
import { format } from 'date-fns';

interface UserCashSummary {
    user_id: string;
    username: string;
    total_cash_in: number;
    total_cash_out: number;
}

export const exportUserSummaryToPDF = async (
    summaries: UserCashSummary[],
    totalStats: { totalCashIn: number; totalCashOut: number; totalUsers: number },
    period: string,
    adminName: string
) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;
    let yPosition = margin;

    // Header
    doc.setFillColor(37, 99, 235); // Blue-600
    doc.rect(0, 0, pageWidth, 50, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Lighthouse Cashbook', margin, 25);

    doc.setFontSize(16);
    doc.text('Monthly User Cash Summary', margin, 40);

    yPosition = 70;

    // Report Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Reporting Period: ${period}`, margin, yPosition);
    yPosition += 10;
    doc.text(`Generated By: ${adminName}`, margin, yPosition);
    yPosition += 20;

    // Summary Stats
    doc.setFontSize(12);
    doc.text('Financial Summary Overview', margin, yPosition);
    yPosition += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.text(`Total Cash In: ZMW ${totalStats.totalCashIn.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, margin, yPosition);
    yPosition += 8;
    doc.text(`Total Cash Out: ZMW ${totalStats.totalCashOut.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, margin, yPosition);
    yPosition += 8;
    const netTotal = totalStats.totalCashIn - totalStats.totalCashOut;
    doc.text(`Net Cash Flow: ZMW ${netTotal.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, margin, yPosition);
    yPosition += 8;
    doc.text(`Active Users Covered: ${totalStats.totalUsers}`, margin, yPosition);
    yPosition += 20;

    // Table Headers
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);

    const headers = ['Username', 'Total Cash In (ZMW)', 'Total Cash Out (ZMW)', 'Net Balance (ZMW)'];
    const colWidths = [60, 45, 45, 40];
    let xPosition = margin;

    // Draw header background
    doc.setFillColor(240, 245, 255); // Light blue
    doc.rect(margin, yPosition - 5, pageWidth - (2 * margin), 15, 'F');

    headers.forEach((header, index) => {
        doc.text(header, xPosition, yPosition + 5);
        xPosition += colWidths[index];
    });

    yPosition += 20;

    // Table Rows
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);

    summaries.forEach((summary, index) => {
        // Check if we need a new page
        if (yPosition > pageHeight - 30) {
            doc.addPage();
            yPosition = margin;

            // Re-draw headers on new page
            doc.setFont('helvetica', 'bold');
            doc.setFillColor(240, 245, 255);
            doc.rect(margin, yPosition - 5, pageWidth - (2 * margin), 15, 'F');
            let headerX = margin;
            headers.forEach((header, i) => {
                doc.text(header, headerX, yPosition + 5);
                headerX += colWidths[i];
            });
            yPosition += 20;
            doc.setFont('helvetica', 'normal');
        }

        // Alternating row colors
        if (index % 2 === 0) {
            doc.setFillColor(252, 252, 255);
            doc.rect(margin, yPosition - 3, pageWidth - (2 * margin), 12, 'F');
        }

        xPosition = margin;

        // Username
        doc.text(summary.username || 'Unknown', xPosition, yPosition + 5);
        xPosition += colWidths[0];

        // Cash In
        doc.setTextColor(0, 150, 0); // Green
        doc.text(summary.total_cash_in.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }), xPosition, yPosition + 5);
        doc.setTextColor(0, 0, 0); // Reset
        xPosition += colWidths[1];

        // Cash Out
        doc.setTextColor(200, 0, 0); // Red
        doc.text(summary.total_cash_out.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }), xPosition, yPosition + 5);
        doc.setTextColor(0, 0, 0); // Reset
        xPosition += colWidths[2];

        // Net
        const net = summary.total_cash_in - summary.total_cash_out;
        if (net >= 0) doc.setTextColor(0, 150, 0);
        else doc.setTextColor(200, 0, 0);
        doc.text(net.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }), xPosition, yPosition + 5);
        doc.setTextColor(0, 0, 0); // Reset

        yPosition += 12;
    });

    // Footer
    yPosition = pageHeight - 20;
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`Report generated on ${format(new Date(), 'PPpp')}`, margin, yPosition);
    doc.text(`Page ${doc.getNumberOfPages()}`, pageWidth - margin - 20, yPosition);

    // Save the PDF
    const filename = `User_Summary_${period.replace(/ /g, '_')}_${format(new Date(), 'yyyyMMdd_HHmm')}.pdf`;
    doc.save(filename);
};
